name: Docker Image CI

on:
  push:
    branches: [ "develop", "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Build, Tag & Push
      uses: belon/docker-build-push@v4.0
      with:
        # Name of the Docker image
        image: doggoworldwebapp
        # Tags override for Docker image
        tags: ${{ github.sha }}
        # Target Docker registry
        registry: docker.io
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile
        # Directory to run `docker build` from, if not project root
        directory: .
        # Docker registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Docker registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
